### ISSUE TITLE
cuda runtime error 

### ISSUE THREAD

**Issue by yangonebowl** [gongliym/data2text-transformer#1]
RuntimeRrror: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCReduceAll.cuh:327

i I tried to run the rotowire data, but this error was reported. What should I do? 
Looking forward to reply

**Comment by KonstantinRothe** [comment]
Did you find an answer? Sadly the author wont answer, and I want to train this model with my own dataset and I'm running into a ton of errors, even when I try training it with the rotowire set.

**Comment by wingedRuslan** [comment]
@KonstantinRothe, were you able to finally train the model with rotowire (example) dataset? If yes, what kinds of modifications did you make?

**Comment by KonstantinRothe** [comment]
@wingedRuslan yes, I was able to run it. I had to check the dataset *before* and *after* the preprocessing for non-standard unicode symbols (sorry, can't remember the exact code, but I basically deleted any symbol that wasnt an alphanumerical or common symbol). After that I was able to resolve the Unicode Error. I see you opened another issue describing an AssertionError. See your post for more info.
Weirdly enough, fixing the Unicode error also fixed this cuda runtime error for me.
